### ISSUE TITLE
Crash on Check for cheap deals > Wantslist

### ISSUE THREAD

**Issue by magicmastermindmurks** [alexander-pick/MKMTool#37]
First of all thanks for the amazing work!

Hi, I am experiencing constant crashes while trying to use the check for cheap deals module on wantslists. Size of the wantslist doesn't matter. These are my settings:

> 10% below
> 0 shipping addition
> 100 max card price
> [] trend
> [] domestic
> [x] international
> all lang
> lp condition
> no extra box ticked

This is the error message I get:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at MKMTool.CheckWantsView.checkListRun(String listID, Double maxAllowedPrice, Double shippingAdd, Double percentBelow, Boolean checkTrend)
   at MKMTool.CheckWantsView.<>c__DisplayClass6_0.<checkListButton_Click>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MKMTool.CheckWantsView.<checkListButton_Click>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`

**Comment by tomasjanak** [comment]
They changed how isFoil, isSigned etc. is stored, now when it's set to "Any", they don't send the isFoil tag at all, not even as empty. I'll fix it by the end of next week.

**Comment by magicmastermindmurks** [comment]
Thanks for the reply and even more for fixing it!
